#!/usr/bin/env bash
# install.sh: install org + apply_patch using symlinks so org always points to repo.

set -euo pipefail
ROOTDIR="$(cd "$(dirname "$0")" && pwd)"

# Sanity checks
[[ -f "$ROOTDIR/org" ]]         || { echo "install.sh: missing ./org" >&2; exit 1; }
[[ -f "$ROOTDIR/runner.ts" ]]   || { echo "install.sh: missing ./runner.ts" >&2; exit 1; }
[[ -f "$ROOTDIR/apply_patch" ]] || { echo "install.sh: missing ./apply_patch" >&2; exit 1; }

# Make sure scripts are executable
chmod 0755 "$ROOTDIR/org" || true
chmod 0755 "$ROOTDIR/apply_patch" || true

# Install apply_patch (copy)
sudo install -m 0755 "$ROOTDIR/apply_patch" /usr/local/bin/apply_patch
echo "[install.sh] Installed apply_patch -> /usr/local/bin/apply_patch"

# Remove any stale org wrapper
sudo rm -f /usr/local/bin/org

# Install org as a symlink pointing back into the repo
sudo ln -s "$ROOTDIR/org" /usr/local/bin/org
echo "[install.sh] Symlinked org -> /usr/local/bin/org -> $ROOTDIR/org"

echo "[install.sh] Done. Run 'org' from ANY directory; agents operate in that directory."



CONF_DIR="$APPDIR/src/config"
WL_FILE="$CONF_DIR/paths.ts"
mkdir -p "$CONF_DIR"
if [ ! -f "$WL_FILE" ]; then
  cat >"$WL_FILE" <<'TS'
/**
 * Auto-generated by install.sh — edit to taste.
 * Items may use "~". Only existing directories are used at runtime.
 */
export const PATHS = [
  "~/.bun/bin",
  "~/.cargo/bin",
  "/usr/local/bin",
  "/usr/bin",
  "/bin"
] as const;
TS
  echo "[install.sh] Created $WL_FILE"
fi
