# .org/config/org.lima.yaml
images:
  - location: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-arm64.img"
    arch: "aarch64"

cpus: 4
memory: "8GiB"
disk: "60GiB"   # VM disk; host ~/dev is bind-mounted and does NOT consume this

mounts:
  - location: "~/dev"
    mountPoint: "/home/{{.User}}.linux/dev"
    writable: true

provision:
  - mode: system
    script: |
      set -euxo pipefail
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y sudo ufw git curl ca-certificates jq unzip bash-completion
      printf '%s ALL=(ALL) NOPASSWD:ALL\n' '{{.User}}' > /etc/sudoers.d/90-{{.User}}-nopasswd
      chmod 0440 /etc/sudoers.d/90-{{.User}}-nopasswd

  - mode: user
    script: |
      set -euxo pipefail
      mkdir -p ~/.bashrc.d
      cat >~/.bashrc.d/org.sh <<'EOF'
      PS1='\[\e[36m\]\u@org:\w\[\e[0m\]$ '
      [[ ":$PATH:" != *":$HOME/.local/bin:"* ]] && export PATH="$HOME/.local/bin:$PATH"
      [[ ":$PATH:" != *":$HOME/.bun/bin:"*   ]] && export PATH="$HOME/.bun/bin:$PATH"
      EOF
      grep -q '.bashrc.d' ~/.bashrc 2>/dev/null || \
        printf '\nfor f in ~/.bashrc.d/*.sh; do [ -r "$f" ] && . "$f"; done\n' >> ~/.bashrc

      mkdir -p "$HOME/dev"
      if [ ! -d "$HOME/dev/org/.git" ]; then
        git clone --depth=1 https://github.com/tjamescouch/org.git "$HOME/dev/org"
      else
        git -C "$HOME/dev/org" fetch --quiet || true
        git -C "$HOME/dev/org" reset --hard origin/HEAD || true
      fi

      # Non-interactive install; ends with firewall locked down
      ORG_INSTALL_SUDO=yes ORG_INSTALL_LAUNCH=no \
      bash "$HOME/dev/org/install.sh" --build-image || true

ssh:
  localPort: 0
firmware:
  legacyBIOS: false
