# org.lima.yaml — canonical, one-command install with pre-warmed image
images:
  - location: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-arm64.img"
    arch: "aarch64"

cpus: 4
memory: "8GiB"
disk: "40GiB"

mounts:
  - location: "~/dev"
    mountPoint: "/home/{{.User}}.linux/dev"
    writable: true

provision:
  - mode: system
    script: |
      set -euxo pipefail
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      # Podman + essentials for rootless usage and our provisioning
      apt-get install -y \
        podman uidmap slirp4netns fuse-overlayfs iptables \
        ufw git curl ca-certificates jq unzip bash-completion
      # Passwordless sudo for our user
      printf '%s ALL=(ALL) NOPASSWD:ALL\n' '{{.User}}' > /etc/sudoers.d/90-{{.User}}-nopasswd
      chmod 0440 /etc/sudoers.d/90-{{.User}}-nopasswd
      # Make sure sshd is enabled for limactl shell
      systemctl enable --now ssh

  - mode: user
    script: |
      set -euxo pipefail

      # Shell init
      grep -q "\. ~/.bashrc" ~/.bash_profile 2>/dev/null || \
        printf '[ -r ~/.bashrc ] && . ~/.bashrc\n' >> ~/.bash_profile
      mkdir -p ~/.bashrc.d
      grep -q ".bashrc.d" ~/.bashrc 2>/dev/null || \
        printf '\nfor f in ~/.bashrc.d/*.sh; do [ -r "$f" ] && . "$f"; done\n' >> ~/.bashrc
      cat >~/.bashrc.d/10-org-prompt.sh <<'EOF'
      export PROMPT_DIRTRIM=2
      PS1='\[\e[1;95m\][VM]\[\e[0m\] \[\e[1;36m\]\u@\h\[\e[0m\]:\[\e[1;32m\]\w\[\e[0m\]\$ '
      EOF

      # --- PATH conveniences ---
      cat >~/.bashrc.d/20-org-path.sh <<'EOF'
      [[ ":$PATH:" != *":$HOME/.local/bin:"* ]] && export PATH="$HOME/.local/bin:$PATH"
      [[ ":$PATH:" != *":$HOME/.bun/bin:"*   ]] && export PATH="$HOME/.bun/bin:$PATH"
      EOF

      # --- Host LLM endpoint (Lima maps host loopback to 192.168.5.2) ---
      cat >~/.bashrc.d/30-org-llm.sh <<'EOF'
      export ORG_LLM_BASE_URL="http://192.168.5.2:11434"
      # mirror for libs that read LLM_BASE_URL
      export LLM_BASE_URL="${LLM_BASE_URL:-$ORG_LLM_BASE_URL}"
      EOF
      # Ensure repo present (bind-mounted at ~/dev)
      mkdir -p "$HOME/dev"
      if [ ! -d "$HOME/dev/org/.git" ]; then
        git clone --depth=1 https://github.com/tjamescouch/org.git "$HOME/dev/org"
      else
        git -C "$HOME/dev/org" pull || true
      fi

      # Run installer in the repo — ALWAYS build the sandbox image here.
      # This provision step blocks until done; failure stops limactl start.
      ORG_HOST_LO_IP=192.168.5.2 ORG_HOST_LLM_PORT=11434 \
      ORG_LLM_BASE_URL="http://192.168.5.2:11434" \
      ORG_ENGINE=podman \
      SANDBOX_BACKEND=podman \
      pushd "$HOME/dev/org/"
      bash ./install.sh --build-image > "$HOME/org-install.log" 2>&1
      popd

ssh:
  localPort: 0
firmware:
  legacyBIOS: false
