arch: aarch64
images:
  - location: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-arm64.img"

disk: 60GiB

# Minimal networking for apt-get; UFW will lock down after provisioning
networks:
  - lima: shared

mounts:
  # Host ~/dev -> Guest ~/dev
  - location: "~/dev"
    mountPoint: "/home/{{.User}}.linux/dev"
    writable: true

  # Ephemeral scratch
  - location: "tmpfs"
    mountPoint: "/home/{{.User}}.linux/scratch"
    writable: true

ssh:
  loadDotSSHPubKeys: true

provision:
  - mode: system
    script: |
      apt-get update
      apt-get install -y curl git ufw podman openssh-server sudo
      systemctl enable --now ssh

      # UFW policy
      ufw default deny incoming
      ufw default deny outgoing
      ufw allow 22/tcp
      ufw allow out to 127.0.0.1
      ufw --force enable

  - mode: user
    script: |
      mkdir -p "$HOME/dev"
      curl -fsSL https://bun.sh/install | bash
      echo 'export BUN_INSTALL=$HOME/.bun' >> ~/.bashrc
      echo 'export PATH=$BUN_INSTALL/bin:$PATH' >> ~/.bashrc
