# .org/config/org.lima.yaml
# Lima profile for `org` VM
# - Root disk: 50 GiB
# - Mounts:
#     host ~/dev   -> guest /home/org/dev
#     tmpfs scratch -> guest /home/org/scratch
# - Networking: disabled in Lima config, but ufw restricts guest
# - User: fixed "org"

arch: aarch64
images:
  - location: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-arm64.img"

disk: 50GiB

# Disable Lima-provided networking (no external connectivity)
networks: []

mounts:
  # Development workspace
  - location: "~/dev"
    mountPoint: "/home/org/dev"
    writable: true

  # Scratch space (ephemeral tmpfs)
  - location: "tmpfs"
    mountPoint: "/home/org/scratch"
    writable: true

provision:
  - mode: system
    script: |
      apt-get update
      apt-get install -y curl git ufw podman openssh-server sudo
      systemctl enable --now ssh

      # Hardened defaults, but explicitly open SSH *inbound*
      ufw default deny incoming
      ufw default deny outgoing
      ufw allow 22/tcp             # <-- allow SSH IN
      ufw allow out to 127.0.0.1   # allow LMStudio/Ollama on host
      ufw --force enable
  - mode: user
    script: |
      curl -fsSL https://bun.sh/install | bash
      echo 'export BUN_INSTALL=$HOME/.bun' >> ~/.bashrc
      echo 'export PATH=$BUN_INSTALL/bin:$PATH' >> ~/.bashrc
