/**
 * Auto-generated by install.sh — edit to taste.
 * Items may use "~". Only existing directories are used at runtime.
 */
export const PATHS = [
  "~/.bun/bin",
  "~/.cargo/bin",
  "/usr/local/bin",
  "/usr/bin",
  "/bin"
] as const;
